### ISSUE TITLE
ToDo (DD)

### ISSUE THREAD

**Issue by awillinger** [ari-ayvazyan/RouterManagementProject_RockTheNet#15]
Implement:
- DataSourceImpl
- CommandCentreImpl

For those, call CommandProxy.getCommand(command, device)
command: AddPolicy, PullPolicies, etc.
device: Read from Configuration -> Configuration.getInstance().getDevice()
- PullPolicies

Once Freudensprung has finished the SNMP stuff, simply use the following OID's to query the policies:

.1.3.6.1.4.1.3224.10.1.1.1 -> ID
.1.3.6.1.4.1.3224.10.1.1.3 -> Source Zone
.1.3.6.1.4.1.3224.10.1.1.4 -> Dest. Zone
.1.3.6.1.4.1.3224.10.1.1.5 -> Source Address
.1.3.6.1.4.1.3224.10.1.1.6 -> Dest. Address
.1.3.6.1.4.1.3224.10.1.1.7 -> Service
.1.3.6.1.4.1.3224.10.1.1.8 -> Action
.1.3.6.1.4.1.3224.10.1.1.15 -> Log
.1.3.6.1.4.1.3224.10.1.1.24 -> Name

**Comment by ddjuric-tgm** [comment]
OID[] columns = new OID[]{
                new OID("1.3.6.1.4.1.3224.10.2.1.6"),
                new OID("1.3.6.1.4.1.3224.10.2.1.6.1.0"),
                new OID("1.3.6.1.4.1.3224.10.2.1.6.3.0"),
                new OID("1.3.6.1.4.1.3224.10.2.1.6.8.0"),
                new OID("1.3.6.1.4.1.3224.10.2.1.6.42.0"),
                new OID("1.3.6.1.4.1.3224.10.2.1.6.43.0")};
