### ISSUE TITLE
There is way to much GUI related code in the main class

### ISSUE THREAD

**Issue by truh** [ari-ayvazyan/RouterManagementProject_RockTheNet#19]
Please put all the JavaFX setup code into a separate class(es), so that people who don't work on the GUI have a clear overview on code related to their problems.

**Comment by awillinger** [comment]
Already done in https://github.com/aayvazyan-tgm/RouterManagementProject_RockTheNet/commit/85fd6c795a28ecfd7ec24005b0157b8962096ca8 ?

**Comment by truh** [comment]
nice
