### ISSUE TITLE
Find a suitable EMail library

### ISSUE THREAD

**Issue by truh** [ari-ayvazyan/RouterManagementProject_RockTheNet#8]
For:

Alarm the user visually and per email if the config of the firewall-rules changes. To avoid polling use the SNMP-trap mechanism.

snmtp!

**Comment by awillinger** [comment]
Added in e1b9fd8d860868384c370166bf601e7e4e05cd41

**Comment by truh** [comment]
Could you maybe explain how to send a email via SMTP(s), that's probably all we will need lib for.

**Comment by awillinger** [comment]
It's also described on their webpage, not that hard:

```
Email email = new SimpleEmail();
email.setHostName("smtp.googlemail.com");
email.setSmtpPort(465);
email.setAuthenticator(new DefaultAuthenticator("username", "password"));
email.setSSLOnConnect(true);
email.setFrom("user@gmail.com");
email.setSubject("TestMail");
email.setMsg("This is a test mail ... :-)");
email.addTo("foo@bar.com");
email.send();
```
